### ISSUE TITLE
Trace width on power input (too small at 0.006 inch)

### ISSUE THREAD

**Issue by lewispg228** [svvsdIC/Canary-Electrical#1]
The traces at your initial power input are a little too thin. At 0.006 inch width, they have the potential to heat up (and eventually burn up) if too much current is pulled.

![image](https://user-images.githubusercontent.com/601236/46627338-6e3ca080-caf7-11e8-8fd3-c94af3495ecc.png)

![image](https://user-images.githubusercontent.com/601236/46627388-93311380-caf7-11e8-99f9-719f0661c659.png)

I would suggest bumping up the trace width on all of these segments to at least 0.020 inch like so:

![image](https://user-images.githubusercontent.com/601236/46627441-bbb90d80-caf7-11e8-8ff1-0f9746c59972.png)

You can use the "change" tool (looks like a wrench), then select width and "0.02", then start clicking all the segments of the traces to change their width.

![image](https://user-images.githubusercontent.com/601236/46627578-210cfe80-caf8-11e8-9042-2de70c6027e4.png)

**Comment by maejorguava** [comment]
Hey Pete, I changed the width to .024 inches, just to be safe. Should I also change the width of the N$1 signal going down at that fork in the circuit?

**Comment by maejorguava** [comment]
Also, I was just checking the ERC and using the Errors tool, and they came up with a multitude of errors for both the schematic and board. Should those be of any concern?

**Comment by lewispg228** [comment]
Hey @samuelguava Could you commit (and push) your changes? 

> Should I also change the width of the N$1 signal going down at that fork in the circuit?

Probably not necessary, as that is only heading down to a voltage divider (400K/100K) for reference. That won't see much current at all.

> I was just checking the ERC and using the Errors tool, and they came up with a multitude of errors for both the schematic and board. Should those be of any concern?

Depends, but I think you're okay.

Looking at the currently committed design (v4.3), there are a ton of width errors on all of your traces. This is because they are all included in your net class "5V", which is requiring at least 20 mils (0.020 inch). The proper way to set this up would be to use a "default" net class of 0.006 inch for all your data lines, and then only include your 5V net in the 5V net class.

![image](https://user-images.githubusercontent.com/601236/46970884-abfd7400-d077-11e8-944f-9019eb8752a6.png)

![image](https://user-images.githubusercontent.com/601236/46970930-d3544100-d077-11e8-9cd8-341a924c167a.png)

And I wouldn't worry about your "wire stub" errors. These are just due to funny routing that is hard to see because it's all "under" a pad.

If you ever want to see what the DRC errors are talking about, try double clicking on them from the "DRC Errors" window, (while having the brd file open). It will navigate to the error and highlight it with an angled line and box.

![image](https://user-images.githubusercontent.com/601236/46971088-43fb5d80-d078-11e8-91bb-bbc633a67423.png)

As far as ERC errors in your schematic/brd, I wouldn't worry about those.  When you have a lot of unconnected pins on symbols, Eagle will throw a lot of ERC errors. As long as they are intentional, you can ignore them (or "approve" them in the error window).

Although, I might put a reset button (pull down to GND) on your Xbee reset line. That might come in handy if you want to reset the module without having to cycle power by unplugging and re-plugging in your barrel jack power input.

![image](https://user-images.githubusercontent.com/601236/46971333-e9aecc80-d078-11e8-9580-a76fa5fc0cc2.png)

**Comment by lewispg228** [comment]
Trace width increased. Looks good. However, reset grounding has created another issue.
